+incdir+${TNOC_HOME}/rtl/axi_adapter
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_types_pkg.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_if.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_address_decoder_if.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_write_read_mux.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_write_read_demux.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_slave_write_adapter.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_slave_read_adapter.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_slave_adapter.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_master_write_adapter.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_master_read_adapter.sv
${TNOC_HOME}/rtl/axi_adapter/tnoc_axi_master_adapter.sv
