${NOC_SV_HOME}/rtl/router/noc_port_control_if.sv
${NOC_SV_HOME}/rtl/router/noc_port_control_if_renamer.sv
${NOC_SV_HOME}/rtl/router/noc_port_controller.sv
${NOC_SV_HOME}/rtl/router/noc_input_fifo.sv
${NOC_SV_HOME}/rtl/router/noc_vc_merger.sv
${NOC_SV_HOME}/rtl/router/noc_route_selector.sv
${NOC_SV_HOME}/rtl/router/noc_input_block.sv
${NOC_SV_HOME}/rtl/router/noc_input_block_dummy.sv
${NOC_SV_HOME}/rtl/router/noc_output_switch.sv
${NOC_SV_HOME}/rtl/router/noc_output_block.sv
${NOC_SV_HOME}/rtl/router/noc_output_block_dummy.sv
${NOC_SV_HOME}/rtl/router/noc_router.sv
