${TNOC_HOME}/rtl/router/tnoc_port_control_if.sv
${TNOC_HOME}/rtl/router/tnoc_local_port_controller.sv
${TNOC_HOME}/rtl/router/tnoc_internal_port_controller.sv
${TNOC_HOME}/rtl/router/tnoc_input_fifo.sv
${TNOC_HOME}/rtl/router/tnoc_error_checker.sv
${TNOC_HOME}/rtl/router/tnoc_vc_merger.sv
${TNOC_HOME}/rtl/router/tnoc_route_selector.sv
${TNOC_HOME}/rtl/router/tnoc_input_block.sv
${TNOC_HOME}/rtl/router/tnoc_input_block_dummy.sv
${TNOC_HOME}/rtl/router/tnoc_output_switch.sv
${TNOC_HOME}/rtl/router/tnoc_output_block.sv
${TNOC_HOME}/rtl/router/tnoc_output_block_dummy.sv
${TNOC_HOME}/rtl/router/tnoc_router.sv
